services:
  webtest:
    build: .
    working_dir: /usr/src/app
    tty: true
    volumes:
      - .:/usr/src/app
    environment:
      - RAILS_ENV=test
    ports:
      - "8082:3000"
    expose:
      - "8082"
